apiVersion: v1
kind: Service
metadata:
  name: prs-clusterip
spec:
  type: ClusterIP
  ports:
    - name: wsgi
      port: 8080
      protocol: TCP
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: prs-typesense
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: default
      port: 42
      protocol: TCP
      targetPort: 42
